package br.gov.sp.sme.salaleitura.feature.legal

/** Informações técnicas para operadores adultos; não substituem o aviso do controlador nem constituem consentimento. */
object LegalInfoContent {
    const val creator = "Código em Aula"
    const val instagramHandle = "@codigoemaula"
    const val instagramUrl = "https://www.instagram.com/codigoemaula/"

    val privacySections: List<Pair<String, String>> = listOf(
        "1. Finalidade e uso por educadores" to "Sala de Leitura apoia educadores na organização local do acervo, dos exemplares, dos leitores, empréstimos, devoluções, inventários e relatórios. Não é um serviço de acesso direto por estudantes. O cadastro e a circulação funcionam sem internet e permanecem no banco de dados deste dispositivo.",
        "2. Dados utilizados" to "A unidade pode cadastrar nome, turma ou função, identificador institucional facultativo, fotografia facultativa escolhida na galeria e histórico de circulação, além dos dados das obras. Prefira o cadastro mínimo necessário. Não solicite dados sensíveis, documentos pessoais ou fotografia quando a finalidade puder ser atendida somente pelo nome e turma.",
        "3. Armazenamento local e ausência de sincronização" to "O aplicativo não possui contas online, painel remoto ou sincronização de cadastros. Nomes, fotos, turmas, inventário, acervo e registros de empréstimos não são enviados automaticamente ao criador nem a serviços bibliográficos. A área privada do Android abriga os dados; mantenha o aparelho sob guarda e com sistema atualizado.",
        "4. Internet: somente informações bibliográficas" to "Quando solicitada consulta de metadados por ISBN, o identificador bibliográfico é enviado a catálogos externos como BrasilAPI, Open Library, Google Books ou Crossref; a atualização de faixas ISBN também consulta sua fonte bibliográfica. Essas conexões podem expor endereço IP e informações técnicas aos respectivos provedores. Não são enviados dados de leitores, fotos ou empréstimos. Conferir as políticas dos provedores e operar offline quando não for necessária a consulta é uma decisão do operador.",
        "5. Fotos e câmera" to "A foto é opcional: o operador escolhe uma imagem da galeria, que é redimensionada e armazenada privadamente. Não há reconhecimento facial nem identificação de pessoas pela câmera: a câmera lê códigos de livros e exemplares. Use fotos apenas quando indispensáveis à organização do serviço e observadas as regras da unidade.",
        "6. Exportações e backup" to "Exportações CSV e backups são feitos somente por iniciativa do operador e no destino por ele escolhido. Exportações CSV contêm dados pessoais em texto legível, SEM criptografia; o aplicativo apresenta aviso antes de salvá-las. O novo backup inclui banco de dados e fotos opcionais, protegidos por senha e criptografia autenticada. Backups antigos sem criptografia podem ser importados somente com habilitação explícita e não incluem fotos. Guarde a senha em segurança. Outros aplicativos podem transmitir arquivos quando o usuário escolhe destinos compartilhados ou de nuvem; o autor não recebe esses arquivos automaticamente.",
        "7. Proteção do acesso e conservação" to "A abertura exige o desbloqueio seguro configurado no Android, com nova autenticação após cinco minutos fora do aplicativo; navegar entre telas e registrar empréstimos não exige novo login. Esse bloqueio utiliza o aparelho, não uma conta online, e não diferencia pessoas que compartilham a mesma credencial do dispositivo. Os dados permanecem até correção, remoção, anonimização ou restauração. Perder a senha do backup impede sua recuperação. A unidade define prazos, guarda do aparelho e acesso aos arquivos exportados.",
        "8. Remoção e direitos dos titulares" to "O operador pode editar o cadastro e remover os dados pessoais de um leitor. Se houver empréstimo aberto, deve registrar a devolução antes. Cadastros sem histórico são excluídos; com empréstimos já encerrados, os identificadores pessoais e foto são removidos, preservando a contagem histórica sem identidade do leitor. Arquivos CSV e backups anteriormente exportados não são alterados automaticamente e precisam de gestão pela unidade. Para acesso, correção, eliminação ou dúvidas, procure a organização responsável pelo cadastro.",
        "9. LGPD, ECA Digital e responsabilidades" to "O tratamento de dados locais continua sujeito à Lei Geral de Proteção de Dados (Lei nº 13.709/2018); uso offline não dispensa sua observância. A instituição usuária deve determinar finalidade, hipótese legal, necessidade, controlador e contato, prazos de retenção, base documental e procedimentos para solicitações e incidentes. Dados de crianças e adolescentes requerem observância de seu melhor interesse (art. 14 da LGPD) e proteção aplicável pelo ECA Digital (Lei nº 15.211/2025). O software não presume que um aceite genérico constitua hipótese legal suficiente e sua implantação exige avaliação da unidade. Ser autor do código não implica, por si só, acesso aos registros locais.",
        "10. Atualizações" to "Este texto descreve esta implementação; novas formas de coleta, comunicação ou compartilhamento exigem revisão prévia. A proteção do aplicativo não substitui as políticas da organização, avaliação jurídica contextual e testes no aparelho. Não autoriza publicação de cadastros pessoais."
    )

    val termsSections: List<Pair<String, String>> = listOf(
        "Funções" to "Organização local de obras e exemplares, ISBN, identificação de leitores por nome, empréstimo, devolução, inventário e relatórios. Um ISBN identifica a edição; cada empréstimo registra um exemplar físico específico.",
        "Uso por professores" to "O educador desbloqueia o aplicativo pelo Android uma vez por sessão. Nova verificação ocorre após cinco minutos fora dele, não após cada operação. O sistema não exige conta ou internet para circulação.",
        "Cadastro responsável" to "Cadastre apenas o necessário, não recolha documentos pessoais ou fotos sem necessidade, confira cada exemplar e defina os prazos de empréstimo. As informações pessoais pertencem ao contexto da unidade que as registra; o criador não recebe cadastros automaticamente.",
        "Conexão e limites" to "A pesquisa por ISBN e a atualização de faixas ISBN dependem de provedores externos e podem apresentar dados incompletos. Utilize o preenchimento manual se necessário; cadastros e circulação permanecem locais.",
        "Backups e troca de instalação" to "Crie backup completo criptografado com senha antes de trocar de aparelho. Guarde a senha; backups legados sem criptografia exigem importação consciente e não contêm as fotos antigas. Exportações CSV são legíveis. A instalação de um aplicativo com identificador ou assinatura diferente não atualiza automaticamente o anterior: confirme a restauração de todos os dados antes de desinstalar a versão prévia.",
        "Dados pessoais e direitos" to "A unidade deve definir o controlador, o canal de atendimento, hipóteses legais e prazos de retenção. O operador pode remover ou anonimizar cadastro após a devolução de livros, mas deve cuidar separadamente dos arquivos que exportou. Este texto não é um termo de consentimento automático.",
        "Natureza independente" to "Aplicativo independente desenvolvido pelo Código em Aula, sem homologação institucional implícita. Sua distribuição técnica não significa certificação jurídica da implantação."
    )

    const val about = "Sala de Leitura é um aplicativo independente concebido e desenvolvido pelo Código em Aula para apoiar educadores na organização de acervos e na circulação de livros. Prioriza a operação local e a proteção de dados pessoais. Não é um aplicativo oficial de órgão público ou de rede de ensino. Conheça o criador no Instagram @codigoemaula."
    const val legalReferenceUrl = "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm"
    const val authorityReferenceUrl = "https://www.gov.br/anpd/pt-br/assuntos/noticias/anpd-divulga-enunciado-sobre-o-tratamento-de-dados-pessoais-de-criancas-e-adolescentes"
}
