package br.gov.sp.sme.salaleitura.feature.legal

/** Explanatory copy about the functions actually present in the application. Not a consent form. */
object LegalInfoContent {
    const val creator = "Código em Aula"
    const val instagramHandle = "@codigoemaula"
    const val instagramUrl = "https://www.instagram.com/codigoemaula/"

    val privacySections: List<Pair<String, String>> = listOf(
        "1. Finalidade e funcionamento" to "Sala de Leitura é um aplicativo de organização de obras e exemplares, salas e turmas, leitores, empréstimos, devoluções, inventários e relatórios. O cadastro e a circulação funcionam sem conexão com a internet e são registrados no banco de dados local deste dispositivo.",
        "2. Quais dados são registrados" to "O responsável pela utilização pode cadastrar o nome da unidade e sua identificação, dados bibliográficos, códigos de exemplares, nomes de estudantes e profissionais, vínculo com turma ou função, identificador institucional opcional, foto opcional selecionada da galeria e histórico de empréstimos, prazos e devoluções. Cadastre somente o necessário para organizar o serviço.",
        "3. Dados mantidos no dispositivo" to "O aplicativo não possui conta, sincronização em nuvem, painel remoto, envio automático do acervo ou transmissão de nomes, fotos, turmas e operações de empréstimo ao criador. Os registros ficam no armazenamento privativo do aplicativo no dispositivo. Não há leitura de rostos nem identificação de estudantes ou profissionais pela câmera; a câmera serve para códigos dos livros.",
        "4. Conexão: consulta bibliográfica pelo ISBN" to "A internet é utilizada quando se busca metadados bibliográficos a partir de um ISBN e quando se solicita atualização de faixas ISBN. Nessas solicitações, o ISBN consultado é enviado a serviços externos de catálogos, como BrasilAPI, Open Library, Google Books e Crossref; a atualização das faixas consulta a fonte bibliográfica correspondente. Não são enviados nessa operação nomes de leitores, fotos, turmas, inventário ou histórico de circulação. Como em qualquer acesso à internet, o serviço destinatário pode receber dados técnicos da conexão, como o endereço IP, sujeitos às políticas do próprio provedor. As respostas bibliográficas podem ficar em cache local. A consulta automática exige conexão; as funções de acervo e circulação permanecem utilizáveis sem ela.",
        "5. Fotos, câmera e minimização" to "A foto de um leitor é facultativa, escolhida pelo responsável a partir da galeria, reduzida e copiada para o armazenamento privado do aplicativo. O cadastro por nome é suficiente para selecionar o leitor. Evite registrar dados excessivos e não use fotos se elas não forem necessárias. A câmera lê somente códigos de livros e exemplares.",
        "6. Exportação e cópias de segurança" to "Exportações CSV e arquivos de backup somente são produzidos quando o usuário solicita e escolhe onde salvá-los; o aplicativo não os envia automaticamente à internet. O arquivo de backup contém o banco de dados, inclusive cadastros e circulação, mas a versão atual não inclui os arquivos das fotos opcionais. Arquivos exportados podem ser acessados, copiados ou enviados por outros aplicativos conforme o destino escolhido pelo usuário. Guarde-os em local protegido, limite o acesso e não compartilhe informações pessoais desnecessariamente. Restaurar um backup substitui os dados locais existentes.",
        "7. Proteção, conservação e exclusão" to "O banco e as fotos são gravados na área privada do aplicativo, mas isso não substitui bloqueio de tela, controle de acesso ao aparelho e guarda segura de backups. O aplicativo não oferece criptografia própria nem autenticação individual de usuários. Os registros permanecem no dispositivo até serem alterados, substituídos por restauração ou eliminados juntamente com os dados do aplicativo. Desinstalar ou limpar o armazenamento pode causar perda definitiva de registros sem cópia de segurança; a remoção do aplicativo não apaga arquivos exportados para outros locais.",
        "8. LGPD e responsabilidades" to "A Lei Geral de Proteção de Dados Pessoais (LGPD, Lei nº 13.709/2018) também se aplica ao tratamento local de dados pessoais: operar sem nuvem não significa estar isento da LGPD. A escola ou organização que decide cadastrar e utilizar essas informações deve definir sua finalidade, hipótese legal aplicável, necessidade, acesso, prazo de conservação e procedimentos para atender aos direitos dos titulares. No caso de crianças e adolescentes, deve prevalecer seu melhor interesse (art. 14). A autoria do software, por si só, não torna o criador responsável pelos cadastros locais que ele não recebe. Para acesso, correção ou outras solicitações relativas aos registros, procure o responsável pela unidade que opera o aplicativo.",
        "9. Atualizações destas informações" to "Estas informações descrevem a versão atual. Novas funcionalidades que alterem armazenamento, exportações ou comunicação de dados devem ser acompanhadas de revisão deste texto antes do uso. Não há autorização implícita para publicar dados de estudantes ou profissionais."
    )

    val termsSections: List<Pair<String, String>> = listOf(
        "O que este aplicativo oferece" to "Ferramenta de apoio à gestão local de salas de leitura e bibliotecas: cadastro de obras e exemplares, identificação por ISBN ou código individual, organização de turmas e leitores, circulação, inventário, relatórios e exportação manual.",
        "Como utilizar" to "Cadastre a unidade, adicione obras e seus exemplares, identifique os leitores pelo nome e selecione o exemplar físico correto ao registrar cada empréstimo. Ao devolver, confira o exemplar e seu estado. Um ISBN identifica uma edição e pode corresponder a vários exemplares; a circulação registra o exemplar individual, evitando trocas de volumes.",
        "Uso responsável" to "A unidade que utiliza o aplicativo organiza o acesso ao dispositivo, confere os cadastros, define prazos e orienta os usuários. Utilize apenas dados necessários à finalidade de circulação e observe a legislação aplicável, especialmente a LGPD e a proteção de crianças e adolescentes. O aplicativo não substitui procedimentos internos de gestão, autorização ou segurança da informação.",
        "Funcionamento offline e limitações" to "O cadastro, a consulta ao acervo já registrado e a circulação são locais. A busca de informações bibliográficas por ISBN e a atualização de faixas ISBN dependem de internet e de serviços externos, podendo falhar ou retornar dados incompletos. Confira título, autoria, edição e quantidade antes de salvar; quando necessário, use preenchimento manual.",
        "Cuidados com o backup" to "Faça cópias de segurança antes de trocar de aparelho ou instalar uma versão com assinatura diferente. Confira o local de armazenamento e proteja os arquivos exportados. O backup atual não inclui as fotos opcionais; não apague o aplicativo com dados importantes antes de verificar uma estratégia de migração completa.",
        "Natureza do projeto" to "Aplicativo independente desenvolvido pelo Código em Aula. Seu uso não representa homologação, patrocínio ou responsabilidade de qualquer sistema de ensino ou órgão público. Os dados cadastrados não são disponibilizados automaticamente ao autor."
    )

    const val about = "Sala de Leitura é um aplicativo independente concebido e desenvolvido pelo Código em Aula para apoiar a organização de acervos e a circulação de livros em ambientes educacionais. O projeto prioriza o registro local, a operação offline e a identificação individual de exemplares. Não é um aplicativo oficial de órgão público ou de rede de ensino. Para conhecer o trabalho do criador e acompanhar o projeto, acesse o perfil do Código em Aula no Instagram."
    const val legalReferenceUrl = "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm"
    const val authorityReferenceUrl = "https://www.gov.br/anpd/pt-br/assuntos/noticias/anpd-divulga-enunciado-sobre-o-tratamento-de-dados-pessoais-de-criancas-e-adolescentes"
}
